language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
install:
- pip install -U tox
script: tox
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels:
    - irc.freenode.org#scrapy
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapy
  password:
    secure: bUpnSgikr11B4ddmDUlAEg6ujKVM1Lwd7M7mecdXyMDVDobIOIpKA9GfgajfM9Uh9NDGYERvkIzXAikM4uY3Ltz+QtL4qJ14y7hp0Uw2IfoLcRiea315ieNdEQL2cF6EC6GEo49/Ht9iLLZsrlSZdOnYn+HjopYe58cYYuAHyp8=
  on:
    tags: true
    all_branches: true
    repo: scrapy-plugins/scrapy-djangoitem
    condition: $TOXENV == py27
